networks:
  basicnet:
    external: true

services:
  grafana-loki:
    image: grafana/loki:3.6.3
    user: "0"  # 以 root 运行以避免挂载目录权限问题
    volumes:
      - /data/grafana-loki-config.yaml:/etc/loki/config.yaml
      - /data/grafana-loki-data:/loki
    # ports:
    #   - "3100:3100"      # HTTP 接口
    #   - "9095:9095"      # gRPC 接口
    command: "-config.file=/etc/loki/config.yaml"
    networks:
      - basicnet
    deploy:
      placement:
        constraints:
          - "node.hostname == ${MASTER_HOSTNAME}" 